spring:
  application:
    name: zuul-service

#Tomcat Embedded Server Configuration
server:
  port: 7000

#Zuul Configuration Properties
zuul:
  routes:
    serv-client:
      path: /client-service/**
      serviceId: ClientServiceApplication
    serv-auth:
      path: /auth-service/**
      servideId: AuthorityServiceApplication

#Eureka Configuration Properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka